[package]
name = "aya-log-ebpf"
version = "0.1.0"
edition = "2018"

[dependencies]
aya-bpf = { git = "https://github.com/vadorovsky/aya", branch = "bpf_d_path" }
aya-log-common = { path = "../../aya-log-common" }
aya-log-ebpf-macros = { path = "../aya-log-ebpf-macros" }

[lib]
path = "src/lib.rs"

[profile.dev]
panic = "abort"
debug = 1
opt-level = 2
overflow-checks = false

[profile.release]
panic = "abort"